### ISSUE TITLE
When running gen_cpg.py, there is an error : /usr/bin/env: 'bash\r': No such file or directory when I run "./joern xxx".

### ISSUE THREAD

**Issue by suntianq** [SunLab-GMU/GraphSPD#3]

**Comment by shuwang127** [comment]
Did you run the scripts under the folder `GraphSPD/`? The `joern/` is the sub-folder under the main folder (need to `chmod -R +x ./joern`). All the operations in this repo should be run at the `GraphSPD` path.

**Comment by shuwang127** [comment]
If you can provide the path/command and all the error info, that would be helpful for us to target the error reason.

**Comment by suntianq** [comment]
I have&nbsp;executed&nbsp;&nbsp;chmod -R +x ./joern  in ~/GraphSPD, there is an error when i run gen_cpg.py:
***@***.***:/workspace/GraphSPD# python3 gen_cpg.py  /usr/bin/env: ‘bash\r’: No such file or directory /usr/bin/env: ‘bash\r’: No such file or directory Traceback (most recent call last):   File "/workspace/GraphSPD/locate_and_align.py", line 122, in <module&gt;     idx = filename.index(funcInfo[i][0]) ValueError: 'c' is not in list /usr/bin/env: ‘bash\r’: No such file or directory /usr/bin/env: ‘bash\r’: No such file or directory Traceback (most recent call last):   File "/workspace/GraphSPD/locate_and_align.py", line 122, in <module&gt;     idx = filename.index(funcInfo[i][0]) ValueError: 'c' is not in list /usr/bin/env: ‘bash\r’: No such file or directory /usr/bin/env: ‘bash\r’: No such file or directory Traceback (most recent call last):   File "/workspace/GraphSPD/locate_and_align.py", line 122, in <module&gt;     idx = filename.index(funcInfo[i][0]) ValueError: 'c' is not in list /usr/bin/env: ‘bash\r’: No such file or directory /usr/bin/env: ‘bash\r’: No such file or directory Traceback (most recent call last):   File "/workspace/GraphSPD/locate_and_align.py", line 122, in <module&gt;     idx = filename.index(funcInfo[i][0]) ValueError: 'c' is not in list /usr/bin/env: ‘bash\r’: No such file or directory /usr/bin/env: ‘bash\r’: No such file or directory Traceback (most recent call last):   File "/workspace/GraphSPD/locate_and_align.py", line 122, in <module&gt;     idx = filename.index(funcInfo[i][0]) ValueError: 'c' is not in list /usr/bin/env: ‘bash\r’: No such file or directory /usr/bin/env: ‘bash\r’: No such file or directory Traceback (most recent call last):   File "/workspace/GraphSPD/locate_and_align.py", line 122, in <module&gt;     idx = filename.index(funcInfo[i][0]) ValueError: 'c' is not in list /usr/bin/env: ‘bash\r’: No such file or directory /usr/bin/env: ‘bash\r’: No such file or directory Traceback (most recent call last):   File "/workspace/GraphSPD/locate_and_align.py", line 122, in <module&gt;     idx = filename.index(funcInfo[i][0]) ValueError: 'c' is not in list /usr/bin/env: ‘bash\r’: No such file or directory /usr/bin/env: ‘bash\r’: No such file or directory Traceback (most recent call last):   File "/workspace/GraphSPD/locate_and_align.py", line 122, in <module&gt;     idx = filename.index(funcInfo[i][0]) ValueError: 'c' is not in list /usr/bin/env: ‘bash\r’: No such file or directory /usr/bin/env: ‘bash\r’: No such file or directory Traceback (most recent call last):   File "/workspace/GraphSPD/locate_and_align.py", line 122, in <module&gt;     idx = filename.index(funcInfo[i][0]) ValueError: 'c' is not in list /usr/bin/env: ‘bash\r’: No such file or directory /usr/bin/env: ‘bash\r’: No such file or directory Traceback (most recent call last):   File "/workspace/GraphSPD/locate_and_align.py", line 122, in <module&gt;     idx = filename.index(funcInfo[i][0]) ValueError: 'c' is not in list


OS is ubuntu18.04.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SunLab-GMU/GraphSPD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月26日(星期一) 上午10:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SunLab-GMU/GraphSPD] When running gen_cpg.py, there is an error : /usr/bin/env: 'bash\r': No such file or directory when I run "./joern xxx". (Issue #3)





 
If you can provide the path/command and all the error info, that would be helpful for us to target the error reason.

**Comment by shuwang127** [comment]
Can you simply run `$ pyenv --version` and provide the results?

**Comment by shuwang127** [comment]
`/usr/bin/env: ‘bash\r’: No such file or directory` means your pyenv configuation file contains `\r`, which should be replaced with ''.

**Comment by shuwang127** [comment]
> Can you simply run `$ pyenv --version` and provide the results?

If you find:
```shell
$ pyenv --version
/usr/bin/env: ‘bash\r’: No such file or directory 
```

Use 
```shell
$ cd ~/.pyenv && find . -type f | xargs sed -i $'s/\r$//' && cd -
```

**Comment by suntianq** [comment]
Thank you. I have a new question. I want to test my own commits. How to generate raw_patch file as&nbsp; same as your type.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SunLab-GMU/GraphSPD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月26日(星期一) 中午11:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SunLab-GMU/GraphSPD] When running gen_cpg.py, there is an error : /usr/bin/env: 'bash\r': No such file or directory when I run "./joern xxx". (Issue #3)





  
Can you simply run $ pyenv --version and provide the results?
  
If you find:
 $ pyenv --version /usr/bin/env: ‘bash\r’: No such file or directory 
 
Use
 $ cd ~/.pyenv &amp;&amp; find . -type f | xargs sed -i $'s/\r$//' &amp;&amp; cd -

**Comment by shuwang127** [comment]
If it is a GitHub commit, follow step 1.2 instead of 1.1: python3 get_ab_file.py [owner] [repository] [commitID].

If you test a private commit, you also need to copy the changed files only (both a and b versions) to “ab_files/a” and "ab_files/b". See get_ab_files.py and you can know how to place these files.
