### ISSUE TITLE
how the text description of the patch is used

### ISSUE THREAD

**Issue by klssstis** [SunLab-GMU/GraphSPD#6]
Good afternoon.

judging by the test example, the analysis does not use information from the text description of the patch, the "Subject:"

is this a limitation of the public version, or graphSPD only works with code change lines.

**Comment by shuwang127** [comment]
Right. The original version of GraphSPD only relies on the source code part, but it is also available to include the analysis of commit message. Please refer to https://github.com/shuwang127/patchrnn-demo, where we use RNN to analyze the commit message and source code. You can also use other modern language models to analyze them.

**Comment by klssstis** [comment]
thank you
